export const vendors = [
  {
    id: 1,
    name: "Intel",
    customer: "Medtronic",
    category: "Semiconductor",
    risk: "Low",
    status: "Active",
    lastReview: "Jun 12, 2026",
  },
  {
    id: 2,
    name: "Foxconn",
    customer: "Abbott",
    category: "Manufacturing",
    risk: "Medium",
    status: "Review",
    lastReview: "Jul 18, 2026",
  },
  {
    id: 3,
    name: "Flex",
    customer: "Johnson & Johnson",
    category: "EMS",
    risk: "High",
    status: "CAPA",
    lastReview: "Jul 20, 2026",
  },
  {
    id: 4,
    name: "NVIDIA",
    customer: "Boston Scientific",
    category: "Semiconductor",
    risk: "Low",
    status: "Active",
    lastReview: "Jul 2, 2026",
  },
  {
  id: 5,
  name: "Dell",
  customer: "Cedars-Sinai",
  category: "Hardware",
  risk: "Low",
  status: "Approved",
  lastReview: "Jul 10, 2026",
},
{
  id: 6,
  name: "Oracle",
  customer: "UCLA Health",
  category: "Database",
  risk: "Medium",
  status: "Pending",
  lastReview: "Jul 14, 2026",
},
{
  id: 7,
  name: "Texas Instruments",
  customer: "Mayo Clinic",
  category: "Semiconductor",
  risk: "Low",
  status: "Approved",
  lastReview: "Jul 16, 2026",
},
{
  id: 8,
  name: "Amazon Web Services",
  customer: "Sutter Health",
  category: "Cloud Services",
  risk: "Low",
  status: "Approved",
  lastReview: "Jul 8, 2026",
},
{
  id: 9,
  name: "CrowdStrike",
  customer: "Johns Hopkins",
  category: "Cybersecurity",
  risk: "Medium",
  status: "Under Review",
  lastReview: "Jul 22, 2026",
},
{
  id: 10,
  name: "Palo Alto Networks",
  customer: "Kaiser Permanente",
  category: "Network Security",
  risk: "Low",
  status: "Approved",
  lastReview: "Jul 17, 2026",
},
{
  id: 11,
  name: "Snowflake",
  customer: "Cleveland Clinic",
  category: "Data Platform",
  risk: "Medium",
  status: "Pending",
  lastReview: "Jul 6, 2026",
},
{
  id: 12,
  name: "ServiceNow",
  customer: "Providence",
  category: "Workflow Automation",
  risk: "Low",
  status: "Approved",
  lastReview: "Jul 13, 2026",
},
];